
#print_head "Enable redis service"
#systemctl enable redis &>>${log_file}
#status_check $?
#
#print_head "Start Redis Service"
#systemctl restart redis &>>${log_file}
#status_check $?

- name: Install Redis Repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes  #disables public key

- name: Enable & Install Redis
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"  #installs specific version
    state: installed

- name: Update Redis listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable & start Redis service
  ansible.builtin.systemd:
    state: enabled
    enabled: yes
