- name: Prometheus Server
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server

- name: Prometheus Node-Exporter
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter