
#  if [ "${schema_type}" == "mongo" ]; then
#
#      print_head "Copy MongoDB Repo File"
#      cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>${log_file}
#      status_check $?
#
#      print_head "Install Mongo Client"
#      yum install mongodb-org-shell -y &>>${log_file}
#      status_check $?
#
#      print_head "Load Schema"
#      mongo --host mongodb-dev.devopscourse.online </app/schema/${component}.js &>>${log_file}
#      status_check $?

