groups:
- name: RoboShop
  rules:
  - alert: ServerDown
    expr: up < 1 # If up value is less than 1, decides as the server is down
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: Server Down
  - alert: High CPU Usage
    expr: 100 - (avg by (name) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
    for: 1m
    labels:
        severity: critical
    annotations:
        summary: Server High CPU utilisation

