{
 "title": "RoboShop",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Servers Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"cart.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"catalogue.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"user.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"shipping.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"payment.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 - (((node_memory_Buffers_bytes + node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100)"
    }
   ]
  }
 ]
}