groups:
- name: RoboShop-service-alerts
  rules:
  {% for component in components %}  # Jinja2 template to start for loop

  - alert: Service Down Alert - {{ item }} Service
    expr: node_systemd_unit_state{exported_name="{{ item }}.service", state="active"}
    for: 30s
    labels:
      severity: critical
      appName: {{ item }}
    annotations:
      summary: Service Down on Some Server - Service Name - {{ item }}.service

  {% endfor %}  # Jinga2 template for end For Loop