groups:
- name: RoboShop-service-alerts
  rules:
  {% for component in components %}  # Jinja2 template to start for loop

  - alert: Service Down Alert - {{ component }} Service
    expr: node_systemd_unit_state{exported_name="{{ component }}.service", state="active"}
    for: 30s
    labels:
      severity: critical
      appName: "{{ component }}"
    annotations:
      summary: Service Down on Some Server - Service Name - {{ component }}.service
  {% endfor %}  # Jinga2 template for end For Loop